apiVersion: apps/v1
kind: Deployment
metadata:
  name: banana-market
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banana-market
  template:
    metadata:
      labels:
        app: banana-market
    spec:
      containers:
        - name: banana-market
          image: banana-market:v1
          ports:
            - containerPort: 8003
          env:
            - name: ALPHA_VANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: alpha-vantage-secret
                  key: ALPHA_VANTAGE_API_KEY
